apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Release.Name }}
    service: backend

spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      service: backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        service: backend
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: APP_PORT
              value: {{ .Values.port | quote }}
            - name: JWT_SECRET_KEY
              value: tlsqiBlr64jo29rNFf5gx1SXXMCMLBTFkcI0YaNoaHUSOrULaJg2R96uUvfznA2w
            - name: ENCRYPT_SECRET_KEY
              value: auF6CtvFD7W60WVWPFxhOToPR2ceLSEG4ifC8E18yMg81SGJvKaPs8v0daih84e7
            - name: DB_HOST
              value: mysql
            - name: DB_USERNAME
              value: krushil
            - name: DB_PASSWORD
              value: test1234
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: alinedb
  