{{- range .Values.microservices }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $.Release.Name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    app: {{ $.Release.Name }}
    service: backend
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      service: backend
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        service: backend
    spec:
      containers:
        - name: {{ $.Release.Name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .port }}
          env:
            - name: APP_PORT
              value: {{ .port | quote }}
            - name: JWT_SECRET_KEY
              value: {{ $.Values.secrets.JWT_SECRET_KEY }}
            - name: ENCRYPT_SECRET_KEY
              value: {{ $.Values.secrets.ENCRYPT_SECRET_KEY }}
            - name: DB_HOST
              value: mysql
            - name: DB_USERNAME
              value: krushil
            - name: DB_PASSWORD
              value: test1234
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: alinedb
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: {{ .port }}
    targetPort: {{ .port }}
    protocol: TCP
    name: {{ $.Release.Name }}-port
  selector:
    app: {{ $.Release.Name }}
{{- end }}
