apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: krushilnaik/aline-gateway
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_SERVICE_HOST
              value: {{ .Release.Name }}-service-host
            - name: APP_PORT
              value: "80"
          resources:
            limits:
              memory: "400Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 80
