{{- range .Values.microservices.backend }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace | default "default" }}
  name: {{ .name }}
  labels:
    release: {{ $.Release.Name }}
    app: {{ .name }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .port }}
          env:
            - name: APP_PORT
              value: {{ .port | quote }}
            - name: JWT_SECRET_KEY
              value: {{ $.Values.secrets.JWT_SECRET_KEY }}
            - name: ENCRYPT_SECRET_KEY
              value: {{ $.Values.secrets.ENCRYPT_SECRET_KEY }}
            - name: DB_HOST
              value: {{ $.Values.dbCredentials.host }}
            - name: DB_USERNAME
              value: {{ $.Values.dbCredentials.username }}
            - name: DB_PASSWORD
              value: {{ $.Values.dbCredentials.password }}
            - name: DB_PORT
              value: {{ $.Values.dbCredentials.port | default "3306" | quote }}
            - name: DB_NAME
              value: {{ $.Values.dbCredentials.database }}

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.namespace | default "default" }}
  name: {{ .name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: {{ .port }}
    targetPort: {{ .port }}
    protocol: TCP
    name: {{ .name }}-port
  selector:
    app: {{ .name }}
{{- end }}
