apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-host
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    release: {{ .Release.Name }}
  ports:
  {{- range $i, $val := .Values.microservices.backend }}
  - port: {{ $val.port }}
    targetPort: {{ $val.port }}
    protocol: TCP
    name: {{ $val.name }}
  {{ end -}}
